version: '3.9'

services:
  blockscout-redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  blockscout-db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  blockscout-db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  blockscout-backend:
    depends_on:
      - blockscout-db
      - blockscout-redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - blockscout-db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
        CHAIN_ID: '1337'

  blockscout-visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  blockscout-sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  blockscout-frontend:
    depends_on:
      - blockscout-backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  blockscout-stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  blockscout-stats-db:
    depends_on:
      blockscout-stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  blockscout-stats:
    depends_on:
      - blockscout-stats-db
      - blockscout-backend
    extends:
      file: ./services/stats.yml
      service: stats

  blockscout-user-ops-indexer:
    depends_on:
      - blockscout-db
      - blockscout-backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer

  blockscout-proxy:
    depends_on:
      - blockscout-backend
      - blockscout-frontend
      - blockscout-stats
    extends:
      file: ./services/nginx-expose.yml
      service: proxy
